server:
  tomcat:
    uri-encoding: utf-8
  port: 2188
spring:
  application:
    name: saki
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 修改称自己的地址数据库
    url: jdbc:mysql://127.0.0.1:3306/dbname?serverTimezone=UTC&useunicode=true&characterEncoding=utf8
    # 修改成自己的用户名
    username: root
    # 修改成自己的密码
    password: 123456
  redis:
    #Linux主机地址
    host: 127.0.0.1
    #端口 修改成自己的端口
    port: 6379
    #密码   修改成自己的密码
    password: ????
    #超时时间
    timeout: 3000000
    jedis:
      pool:
        #最大连接数目
        max-active: 10
        #连接最大等待时间
        max-wait: 30000ms
        #连接最大等待时间
        max-idle: 10
    database: 0
mybatis:
  configuration:
    # 开启自动驼峰命名
    map-underscore-to-camel-case: true
  # mapper xml 位置
  mapper-locations: classpath:mapper/*Mapper.xml
